theme: jekyll-theme-hacker

# Name of website
title: My Website

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# Output options (more information on Jekyll's site)
timezone: "America/Toronto" 
markdown: kramdown 
highlighter: rouge 
permalink: /:year-:month-:day-:title/ 
paginate: 5 

kramdown:
  input: GFM 
  
# Exclude these files from production site
exclude:
  - CHANGELOG.md 
  - CNAME 
  - Gemfile 
  - Gemfile.lock 
  - LICENSE 
  - README.md 
  - screenshot.png 
  - docs/ 

plugins:
  - jekyll-paginate 
  - jekyll-sitemap 

